/**
 * One-shot quality upgrade for aws-1.1 / 1.2 / 1.3 traditional questions.
 * Preserves id, isPremium, part_id, resposta_correta; rewrites stems/alts/expl as needed.
 * Run: node aws/scripts/_upgrade_quality_aws.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PARTS = path.join(ROOT, "parts");

function Q(id, premium, enunciado, alts, rc, expl, part) {
  if (alts.length !== 4) throw new Error(`id ${id} alts`);
  if (rc < 0 || rc > 3) throw new Error(`id ${id} rc`);
  // Ensure ≥220 with scenario tip if author draft was short
  if (expl.length < 220) {
    expl =
      expl.trim() +
      " No cenário SAA, amarre a escolha ao requisito (segurança, path de rede ou custo) e descarte distractors que misturam domínios sem evidência no enunciado.";
  }
  if (expl.length < 220) throw new Error(`id ${id} expl ${expl.length}: ${expl.slice(0, 60)}`);
  if (/^A resposta correta é/i.test(expl)) throw new Error(`id ${id} bad start`);
  return {
    id,
    question_type: "traditional",
    isPremium: premium,
    enunciado,
    alternativas: alts,
    resposta_correta: rc,
    explicacao_profunda: expl,
    part_id: part,
  };
}

const p11 = "aws-1.1";
const p12 = "aws-1.2";
const p13 = "aws-1.3";

const q11 = [
  Q(1, false,
    "Equipe nova pede AdministratorAccess 'para ir mais rápido'. Qual design IAM atende least privilege no SAA?",
    [
      "Conceder só as Actions e Resources necessários à função (ex. Deploy em prefixos S3 específicos)",
      "Anexar AdministratorAccess a todos os developers por padrão e revisar depois",
      "Usar Effect Deny em todas as policies e liberar via ticket manual",
      "Desabilitar MFA no console para reduzir fricção de onboarding",
    ], 0,
    "Least privilege limita Allow ao mínimo do job (ações e ARNs concretos), reduzindo blast radius se a credencial vazar. AdministratorAccess universal falha porque concede bem mais do que o deploy precisa e é o anti-pattern clássico de prova. Tip de prova: se a opção fala em 'admin agora, restringe depois', descarte em favor de permissões mínimas desde o início.",
    p11),
  Q(2, false,
    "App em EC2 precisa ler DynamoDB e gravar em S3 sem access key no disco. Qual identidade usar?",
    [
      "IAM user com senha e access key no user-data",
      "IAM role associada via instance profile (credenciais temporárias no IMDS)",
      "Grupo IAM vazio sem policy, apenas para 'organização'",
      "Root user da conta com MFA desligado na instância",
    ], 1,
    "Workloads em EC2 usam role + instance profile: o IMDS entrega sessão STS rotativa, sem key estática no host. Access key de user no user-data é o anti-pattern que a prova pune. Tip de prova: se o cenário é serviço AWS falando com outro serviço AWS, a resposta padrão de identidade é role, não user/root.",
    p11),
  Q(3, false,
    "EC2 não assume a role S3ReadRole apesar de permissions S3 corretas. Qual documento define quem pode AssumeRole?",
    [
      "Apenas a bucket policy do S3 de destino",
      "Apenas a tag Name da VPC",
      "A trust policy (AssumeRolePolicyDocument) da role",
      "O Security Group da ENI da instância",
    ], 2,
    "A trust policy lista Principals (serviço EC2, conta, user) autorizados a sts:AssumeRole; sem trust adequado a role não é assumida mesmo com AmazonS3ReadOnlyAccess anexada. Bucket policy e SG não substituem trust de IAM role. Tip de prova: erro 'not authorized to perform sts:AssumeRole' → confira trust primeiro, não só a policy de dados.",
    p11),
  Q(4, false,
    "Policy A Allow s3:DeleteObject e policy B Deny s3:DeleteObject no mesmo principal. Resultado da avaliação IAM?",
    [
      "Allow sempre vence se estiver em managed policy",
      "A ação fica Allow só fora do horário comercial",
      "O root user é desabilitado automaticamente",
      "Deny explícito prevalece e a ação é negada",
    ], 3,
    "Na lógica IAM, Deny explícito tem precedência sobre qualquer Allow; por isso AccessDenied com 'explicit deny' não se resolve só empilhando outro Allow *. Managed vs inline não muda essa regra de precedência. Tip de prova: se a mensagem cita explicit deny, o próximo passo é achar e ajustar o statement Deny, não criar Allow genérico.",
    p11),
  Q(5, false,
    "Time de 12 pessoas precisa das mesmas permissões de suporte SQS/S3. Como organizar com least privilege operacional?",
    [
      "Colocar users em um IAM group (ex. Support-L2) e anexar policies ao group",
      "Dar access key de root compartilhada no canal do time",
      "Criar 12 roles EC2 diferentes só para login de console",
      "Desligar CloudTrail para reduzir ruído de auditoria",
    ], 0,
    "Groups aplicam o mesmo conjunto de policies a vários users humanos, facilitando least privilege por função. Root keys compartilhadas e desligar CloudTrail são falhas graves de segurança e auditoria. Tip de prova: humanos no console → users + groups; workloads → roles.",
    p11),
  Q(6, false,
    "Após sts:AssumeRole bem-sucedido, o que o caller recebe para chamar APIs?",
    [
      "Um certificado ACM permanente de 1 ano",
      "Credenciais temporárias (access key, secret e session token) da sessão",
      "Um Elastic IP fixo associado à role",
      "Uma AMI nova com a policy embutida",
    ], 1,
    "AssumeRole devolve credenciais de curta duração via STS, reduzindo impacto de vazamento versus keys de longo prazo. ACM, EIP e AMI não são o output de AssumeRole. Tip de prova: 'temporário/sessão/STS' na resposta costuma bater com role assumption.",
    p11),
  Q(7, false,
    "User ana.silva não faz s3:PutObject. Allow Put está só no group Billing; ana está apenas em Helpdesk. Causa mais provável?",
    [
      "Falta de Internet Gateway na VPC do endpoint S3",
      "KMS key rotation desligada na conta",
      "A policy não está no principal efetivo (group/user errado) — falta attach correto",
      "CloudFront price class 100 bloqueia PutObject de API",
    ], 2,
    "Permissões IAM efetivas vêm do que está anexado ao user (direto ou via groups dos quais é member). Estar em Helpdesk sem a policy de Put explica a falha; mover ana para o group certo ou anexar a policy resolve. IGW/KMS/CloudFront não são a primeira causa de PutObject IAM. Tip de prova: checklist AccessDenied → 'quem é o principal e quais policies estão attached?'.",
    p11),
  Q(8, false,
    "App Node em EC2 grava DynamoDB. Qual anti-pattern de identidade o SAA mais pune?",
    [
      "Usar VPC endpoint para DynamoDB",
      "Usar role com dynamodb:PutItem no ARN da tabela",
      "Habilitar IMDSv2 na instância",
      "Gravar access key de IAM user no código ou user-data",
    ], 3,
    "Keys estáticas no host são difíceis de rotacionar e vazam com o disco/imagem; o design esperado é role + instance profile. VPC endpoint e IMDSv2 são boas práticas, não o anti-pattern. Tip de prova: se a opção coloca AKIA... no código, está errada no desenho Associate.",
    p11),
  Q(9, false,
    "Ao revisar uma identity-based policy JSON, quais elementos formam o núcleo de um Statement?",
    [
      "Effect, Action e Resource (Condition opcional)",
      "Somente CIDR de origem e porta de destino",
      "Somente AMI ID e instance type da EC2",
      "Somente o record type do Route 53",
    ], 0,
    "Statements IAM usam Effect Allow/Deny, Action da API e Resource ARN; Condition afina o contexto (MFA, IP, tags). CIDR/porta são de SG/NACL; AMI e DNS não definem autorização IAM. Tip de prova: confunda IAM com SG e a resposta errada fala em porta/CIDR.",
    p11),
  Q(10, false,
    "AccessDenied em uma API: qual primeiro comando CLI confirma quem está autenticado?",
    [
      "aws ec2 describe-vpcs",
      "aws sts get-caller-identity",
      "aws s3 mb s3://teste-temp",
      "aws configure list-profiles sem inspecionar o ARN ativo",
    ], 1,
    "get-caller-identity mostra Account, UserId e Arn do principal efetivo (user ou assumed-role), base do TShoot de permissão. describe-vpcs e criar bucket não identificam o caller. Tip de prova: 'quem sou eu nestas credenciais?' → sempre STS get-caller-identity primeiro.",
    p11),
  Q(11, true,
    "Role S3ReadRole tem AmazonS3ReadOnlyAccess, mas EC2 não obtém credenciais. Trust lista só lambda.amazonaws.com e não há instance profile. Diagnóstico?",
    [
      "Aumentar o tamanho do volume EBS root",
      "Trocar a AMI para Windows Server",
      "Ajustar trust para ec2.amazonaws.com e associar instance profile com a role à EC2",
      "Desligar o CloudTrail na região",
    ], 2,
    "Permissions S3 não bastam: o serviço EC2 precisa estar na trust e a instância precisa de instance profile. Trust só Lambda + profile ausente explica falha de assume. EBS/AMI/CloudTrail não corrigem trust. Tip de prova: separe permissions policy (o que faz) de trust policy (quem assume).",
    p11),
  Q(12, true,
    "Mensagem: not authorized to perform s3:DeleteObject … with an explicit deny in an identity-based policy. Próximo foco?",
    [
      "Criar outro Allow s3:* na mesma role sem ler o Deny",
      "Passar a usar sempre o root user no pipeline",
      "Desabilitar versioning do bucket como único remédio",
      "Localizar e remover/ajustar o statement Deny que bloqueia DeleteObject",
    ], 3,
    "A própria mensagem aponta explicit deny; Allow adicional não supera Deny na avaliação IAM. Root e versioning não removem o Deny da identity policy. Tip de prova: 'explicit deny' no texto = caçar o Deny antes de qualquer Allow extra.",
    p11),
  Q(13, true,
    "Qual diferença essencial entre IAM user e IAM role no design Associate?",
    [
      "User é identidade de longo prazo (pessoa/app legado); role é assumível e usa credenciais temporárias",
      "Role só existe em regiões GovCloud",
      "User nunca pode ter policies anexadas",
      "Role sempre tem senha de console como user humano",
    ], 0,
    "Users têm credenciais permanentes (senha/keys); roles são assumidas e recebem sessão STS — padrão para serviços e federação. Ambos podem ter policies; role não é GovCloud-only nem login com senha típica de user. Tip de prova: workload AWS → role; humano console → user (ou federation para role).",
    p11),
  Q(14, true,
    "Conta B precisa ler objetos em bucket da conta A. Qual padrão SAA de cross-account?",
    [
      "Compartilhar a senha do root da conta A no chat do time B",
      "Role na conta A com trust para principal da B + permissions de leitura; B AssumeRole (e bucket policy se necessário)",
      "Abrir 0.0.0.0/0 no NACL e ignorar IAM",
      "Desligar S3 Block Public Access e usar ACL pública always",
    ], 1,
    "Cross-account seguro usa role (trust + permissions) e frequentemente bucket policy permitindo o principal de B — sem root password nem bucket público. NACL não concede API S3. Tip de prova: cross-account = trust/AssumeRole + resource policy, nunca root compartilhado.",
    p11),
  Q(15, true,
    "Estagiário recebe policy Allow s3:* no Resource \"*\". Avaliação de least privilege?",
    [
      "É a melhor prática de onboarding SAA",
      "É obrigatório para abrir o console S3",
      "É excesso de privilégio — restringir Actions e ARNs de bucket/prefix necessários",
      "Impede AccessDenied de forma desejável e deve ser mantido",
    ], 2,
    "s3:* em * permite apagar e expor dados além do job do estagiário; o exame espera restringir ações e resources. Console não exige admin de S3. Tip de prova: Resource \"*\" com Action ampla em humano júnior = red flag de least privilege.",
    p11),
  Q(16, true,
    "Durante TShoot, como listar managed policies anexadas a uma role?",
    [
      "aws ec2 authorize-security-group-ingress",
      "aws rds describe-db-instances",
      "aws iam create-user",
      "aws iam list-attached-role-policies --role-name <role>",
    ], 3,
    "list-attached-role-policies mostra as managed policies da role — passo clássico após get-caller-identity. Comandos de SG, RDS ou create-user não listam attaches da role alvo. Tip de prova: 'attached' no verbo CLI = list-attached-*-policies.",
    p11),
  Q(17, true,
    "O que um instance profile faz no design EC2 + IAM?",
    [
      "Associa uma IAM role a instâncias EC2 para o IMDS entregar credenciais",
      "Cria subnets multi-AZ automaticamente",
      "Substitui Customer Managed Keys do KMS",
      "Ativa MFA Delete em todos os buckets S3 sozinho",
    ], 0,
    "Instance profile é o contêiner que liga a role à EC2; sem ele a instância não assume a role. Não cria rede, não substitui KMS e não configura MFA Delete. Tip de prova: EC2 sem credenciais de role → confira association do instance profile.",
    p11),
  Q(18, true,
    "Dezenas de humanos usam o console. Qual organização de permissões é a boa prática?",
    [
      "Distribuir access keys do root a cada pessoa",
      "Users em groups por função (Dev, Ops, ReadOnly) com policies anexadas aos groups",
      "Uma única role EC2 compartilhada como 'login' de todos no console",
      "Desabilitar CloudTrail para não gerar ruído",
    ], 1,
    "Groups por função escalam least privilege e rotação de pessoas; root keys e desligar CloudTrail são inaceitáveis. Role EC2 não é o modelo de login de console humano. Tip de prova: console multi-user → groups; não root keys.",
    p11),
  Q(19, true,
    "Policy Allow com Condition aws:MultiFactorAuthPresent = true. Qual o papel da Condition?",
    [
      "Trocar a região física do hardware do data center",
      "Criar VPC peering automático com outra conta",
      "Restringir o Allow a contextos (ex. MFA presente, IP de origem, tags)",
      "Substituir o Route 53 privado da VPC",
    ], 2,
    "Condition afina quando o Statement se aplica — por exemplo MFA presente, SourceIp corporativo ou aws:ResourceTag — sem mudar topologia física do data center nem DNS da VPC. Opções que falam em peering ou hardware confudem IAM com rede. Tip de prova: Condition = 'só se…'; se a opção fala em hardware ou peering, está fora de IAM.",
    p11),
  Q(20, true,
    "Qual tema está fora do escopo profundo do piloto IAM foundations (aws-1.1)?",
    [
      "Users, groups e least privilege",
      "Roles, trust e instance profile",
      "AccessDenied e Deny explícito",
      "Organizations SCPs profundos e IAM Identity Center lab completo",
    ], 3,
    "O piloto cobre IAM clássico da conta (identities, policies, trust, STS ideia e TShoot). SCPs multi-account e Identity Center full ficam para parts posteriores. Tip de prova: se a questão pedir SCP de Organizations em profundidade, não force só 'group IAM'.",
    p11),
  Q(21, true,
    "Função Lambda precisa dynamodb:Query em uma tabela. Onde anexar o Allow no desenho usual?",
    [
      "Na execution role da função Lambda",
      "No Security Group da Lambda como regra TCP 443",
      "Na NACL da subnet pública apenas",
      "No DHCP option set da VPC",
    ], 0,
    "Lambda usa execution role para APIs AWS; a policy dynamodb:Query vai nessa role. SG/NACL/DHCP controlam rede, não autorização da API DynamoDB. Tip de prova: permissão de serviço AWS → role do compute, não SG.",
    p11),
  Q(22, true,
    "aws sts get-caller-identity retorna Arn …:assumed-role/AppRole/session. Interpretação?",
    [
      "O principal está usando o root user sem MFA",
      "A sessão atual é de uma role assumida (credenciais temporárias de role)",
      "Não há conta AWS válida",
      "O bucket S3 da conta está público",
    ], 1,
    "ARN assumed-role indica sessão STS a partir de role, não root permanente. Isso não implica conta inválida nem S3 público. Tip de prova: assumed-role no Arn = role session; user ARN seria iam::…:user/….",
    p11),
  Q(23, true,
    "Policy Allow s3:GetObject com Resource só arn:aws:s3:::dados (sem /*). Risco em GetObject de arquivos?",
    [
      "Aumenta o custo do NAT Gateway da VPC",
      "Desliga o versioning do bucket",
      "GetObject em objetos pode falhar se o Resource não incluir object ARNs (bucket/* ou prefixo/*)",
      "Força Glacier Instant Retrieval em todos os puts",
    ], 2,
    "GetObject age sobre objetos; Resource costuma ser arn:aws:s3:::bucket/* (ou prefixo). Só o ARN do bucket não cobre keys. NAT, versioning e classe de storage não são a causa dessa falha de ARN. Tip de prova: Get/Put Object → Resource com /*; ações de bucket (ListBucket) usam ARN do bucket.",
    p11),
  Q(24, true,
    "Por que preferir IAM roles a access keys de longo prazo em workloads na AWS?",
    [
      "Roles são mais caras e por isso 'melhores'",
      "Access keys nunca funcionam com S3",
      "Roles não podem ter policies anexadas",
      "Credenciais temporárias rotacionam e reduzem o impacto de vazamento no host",
    ], 3,
    "Sessões STS expiram e o metadata renova; keys AKIA no disco vazam com imagem/backup e são difíceis de rotacionar. Keys funcionam com S3, mas são pior design; roles têm policies sim. Tip de prova: 'longo prazo no host' vs 'temporário/IMDS' decide a questão.",
    p11),
  Q(25, true,
    "Recebeu AccessDenied em uma API no terminal. Qual primeiro passo prático de TShoot?",
    [
      "Confirmar o principal com get-caller-identity e a Action/Resource da mensagem; depois checar policies/trust attached",
      "Recriar a VPC inteira e todas as subnets",
      "Trocar o tipo de instância para bare metal",
      "Apagar o CloudWatch Log Group da aplicação",
    ], 0,
    "Sem saber quem chama e o que foi negado, qualquer mudança de rede ou compute é chute. O checklist é: identidade → Allow → Deny → trust (se role) → resource policy. Tip de prova: AccessDenied de API AWS ≠ primeiro recriar VPC.",
    p11),
  Q(26, true,
    "Qual a diferença útil entre managed policy e inline policy (ideia SAA)?",
    [
      "Inline só funciona em China regions",
      "Managed (AWS ou customer) é reutilizável e versionável; inline fica embutida em um único principal",
      "Inline é obrigatória para toda EC2",
      "Managed policies não podem conter Effect Deny",
    ], 1,
    "Managed policies reutilizam o mesmo documento em vários principals e têm versões; inline vive colada em um user/role. Ambos podem Deny. Tip de prova: reuso entre times → managed; exceção pontual em um principal → inline.",
    p11),
  Q(27, true,
    "User tem senha de console mas nenhuma policy Allow de EC2. Ao tentar RunInstances, o que ocorre?",
    [
      "Sempre funciona porque autenticou no console",
      "A VPC é recriada automaticamente com admin",
      "AccessDenied / not authorized — autenticação não é autorização",
      "O Security Group autoriza a API EC2 sozinho",
    ], 2,
    "Login (authN) não concede APIs (authZ). Sem Allow efetivo, RunInstances falha. SG filtra tráfego de instância, não a API de controle EC2 do user. Tip de prova: senha/console OK + API negada = falta de policy, não 'rede'.",
    p11),
  Q(28, true,
    "Trust policy com Principal { AWS: arn:aws:iam::111122223333:root }. Significado comum em cross-account?",
    [
      "Qualquer principal da conta 111122223333 pode ser candidato a assumir (ainda sujeito a permissões na origem)",
      "Apenas o serviço S3 da conta atual assume a role",
      "Nega permanentemente qualquer AssumeRole",
      "Cria automaticamente um user local na conta da role",
    ], 0,
    "O ARN root da conta parceira representa a conta como principal de trust; quem assume ainda precisa de permissão sts:AssumeRole na conta de origem. Não cria user nem é o serviço S3. Tip de prova: Principal conta (root ARN) = delegação cross-account, não 'usuário root humano logado'.",
    p11),
  Q(29, true,
    "Qual checklist mental de TShoot IAM esta part reforça?",
    [
      "Principal certo → Allow existe → sem Deny → Resource/Action corretos → trust se for role",
      "Só aumentar o tamanho do volume root da EC2",
      "Só mudar o hostname da instância",
      "Só recriar o Internet Gateway",
    ], 0,
    "Isolar identidade, Allow, Deny, ARN e trust resolve a maioria dos AccessDenied de API. Hostname, volume e IGW não substituem esse checklist de autorização. Tip de prova: memorize a ordem principal → allow → deny → resource → trust.",
    p11),
  Q(30, true,
    "Resumo de design seguro para identidades de workload no SAA (esta part):",
    [
      "Root user em todos os pods e funções Lambda",
      "Access key única compartilhada no Slack do time",
      "AdministratorAccess em todo group de desenvolvimento",
      "Roles com least privilege, trust correto e sessão STS; evitar keys de user no host",
    ], 3,
    "O núcleo Associate é role + least privilege + trust/STS, sem root operacional nem keys no chat. AdministratorAccess em massa contradiz arquiteturas seguras. Tip de prova: se a resposta combina role + least privilege + temporário, costuma ser a correta em workload.",
    p11),
];

const q12 = [
  Q(1, false,
    "ALB internet-facing precisa de path à Internet na VPC. O que caracteriza a subnet pública do ALB?",
    [
      "Route table com 0.0.0.0/0 → Internet Gateway e design de exposição controlada",
      "Impossibilidade de ter rota local do CIDR da VPC",
      "Obrigação de NAT Gateway em toda subnet pública",
      "NACL que só permite Deny e nunca Allow",
    ], 0,
    "Subnet pública tem default route para IGW; a rota local do VPC continua existindo para tráfego interno. NAT é típico de saída de privadas, não define 'pública'. Tip de prova: pública = 0.0.0.0/0 → igw; privada típica = 0.0.0.0/0 → nat.",
    p12),
  Q(2, false,
    "EC2 em subnet privada (sem IP público) precisa baixar patches da Internet. Qual componente de saída é o desenho usual?",
    [
      "Internet Gateway anexado diretamente só à ENI privada como default",
      "NAT Gateway em subnet pública e rota 0.0.0.0/0 da privada para o NAT",
      "Security Group com 'Deny explícito' de todo outbound",
      "Transit Gateway obrigatório mesmo em single-VPC simples",
    ], 1,
    "Privadas saem via NAT (target na RT) mantendo a instância sem IP público. IGW na ENI privada não é o padrão; SG não usa Deny explícito como NACL. Tip de prova: privada + updates = NAT + rota; não 'só abrir SG'.",
    p12),
  Q(3, false,
    "Health check do ALB falha com timeout; SG do target allow 8080 do ALB, mas NACL da subnet tem Deny 8080. Qual diferença SG vs NACL explica o caso?",
    [
      "SG é only Deny e NACL é only Allow",
      "Ambos são stateless e idênticos na avaliação",
      "SG é stateful allow-only na ENI; NACL é stateless na subnet e pode Deny — ambas as camadas precisam permitir",
      "NACL só existe em AWS Outposts e pode ser ignorada",
    ], 2,
    "Mesmo com SG allow, Deny na NACL da subnet bloqueia o path. SG e NACL não são equivalentes; NACL não é Outposts-only. Tip de prova: SG ok e ainda timeout → olhe NACL e rotas, não só o SG de novo.",
    p12),
  Q(4, false,
    "Requisito: banco RDS não acessível da Internet pública. Qual design de rede atende?",
    [
      "Subnet pública com Elastic IP no RDS",
      "SG do banco com 0.0.0.0/0 na porta do engine",
      "Rota 0.0.0.0/0 → IGW na subnet do banco",
      "Subnet privada, sem IP público, SG permitindo só o tier de aplicação",
    ], 3,
    "Dados em privada com SG source = SG/CIDR do app minimizam superfície. EIP, 0.0.0.0/0 e IGW na subnet do DB expõem indevidamente. Tip de prova: 'sem acesso Internet ao banco' → private + SG restrito + sem EIP.",
    p12),
  Q(5, false,
    "Planejando multi-AZ, quantas Availability Zones uma única subnet cobre?",
    [
      "Exatamente uma AZ",
      "Sempre todas as AZs da Região ao mesmo tempo",
      "Nenhuma — subnets são globais como IAM",
      "Apenas Local Zones, nunca AZs regionais",
    ], 0,
    "Cada subnet mapeia a uma AZ; HA multi-AZ exige subnets (e recursos) em ≥2 AZ. Subnet não é global como IAM. Tip de prova: uma subnet ≠ multi-AZ; conte subnets por AZ no desenho.",
    p12),
  Q(6, false,
    "EC2 com IP público em subnet 'pública' não sai para a Internet; SG egress allow all. Hipótese mais forte?",
    [
      "Falta de IAM role na instância para 'liberar TCP'",
      "Route table sem 0.0.0.0/0 → IGW ou IGW não anexado à VPC",
      "S3 versioning desligado na conta",
      "Ausência de alarme CloudWatch na CPU",
    ], 1,
    "Com SG aberto e IP público, o path clássico que falta é rota/IGW. IAM role não cria rota de internet; versioning e alarmes não explicam timeout de rede. Tip de prova: pública sem internet → describe-route-tables e IGW attachment.",
    p12),
  Q(7, false,
    "Cliente HTTPS funciona na ida mas respostas falham após endurecer NACL. Por que NACL ser stateless importa?",
    [
      "Porque NACL só protege o Internet Gateway e ignora subnets",
      "Porque NACL ignora portas efêmeras sempre por design imutável",
      "Porque o retorno precisa de regra Allow separada (ida e volta), inclusive portas efêmeras",
      "Porque NACL substitui completamente o Security Group",
    ], 2,
    "Stateless exige allow nas duas direções; falta de allow de retorno em portas altas quebra sessões mesmo com SG stateful ok. NACL não substitui SG. Tip de prova: timeout assimétrico após NACL → regras de retorno/efêmeras.",
    p12),
  Q(8, false,
    "SG do app não tem inbound 8080; processo escuta em 8080. Efeito típico do health check do ALB?",
    [
      "Tráfego 8080 é permitido por default em todo SG",
      "A NACL vira allow all automaticamente",
      "A rota 0.0.0.0/0 é removida da subnet",
      "Conexões inbound na 8080 são negadas (deny implícito do SG) → health timeout",
    ], 3,
    "SG é deny implícito sem Allow; serviço escutando não basta se a ENI filtra a porta. NACL e rotas não mudam sozinhas. Tip de prova: app up + health timeout → SG do target (source = SG do ALB).",
    p12),
  Q(9, false,
    "Onde implantar o NAT Gateway no desenho clássico public/private?",
    [
      "Em subnet pública (com path ao IGW) para servir como target de saída das privadas",
      "Somente dentro da instância RDS Multi-AZ",
      "No usuário root IAM como 'anexo de rede'",
      "Obrigatoriamente em outra Região para cada VPC",
    ], 0,
    "NAT fica em pública e é o next hop 0.0.0.0/0 das RTs privadas. Não vive no RDS nem no IAM. Tip de prova: NAT = pública; consumidores = privadas com rota para nat-…",
    p12),
  Q(10, false,
    "Dois app tiers na mesma VPC precisam se falar sem Internet. Para que serve a rota local (CIDR da VPC)?",
    [
      "Substituir regras de Security Group entre tiers",
      "Entregar tráfego entre recursos no CIDR da VPC sem passar pelo IGW",
      "Forçar todo o tráfego interno para a Internet e de volta",
      "Desabilitar multi-AZ automaticamente",
    ], 1,
    "A rota local cobre o CIDR da VPC e permite comunicação interna; SG/NACL ainda aplicam. Não força Internet nem desliga multi-AZ. Tip de prova: intra-VPC não precisa de IGW — precisa de SG allow entre tiers.",
    p12),
  Q(11, true,
    "SG do target allow 443 do ALB; NACL da subnet tem Deny inbound 443 com número de regra menor que o Allow. Sintoma esperado?",
    [
      "Sempre funciona porque SG tem precedência absoluta sobre NACL",
      "AccessDenied de IAM no listener do ALB",
      "Tráfego 443 pode ser bloqueado na subnet pelo NACL apesar do SG allow",
      "O IGW é removido automaticamente pela AWS",
    ], 2,
    "Path precisa passar SG e NACL; Deny na NACL (avaliado por regra) derruba mesmo com SG allow. Não é IAM do listener nem remoção de IGW. Tip de prova: SG allow + ainda bloqueado → NACL/rotas.",
    p12),
  Q(12, true,
    "App stateless atrás de ALB com requisito multi-AZ. Qual desenho mínimo de subnets de app?",
    [
      "Uma única subnet privada em uma AZ",
      "Pelo menos duas subnets privadas em AZs diferentes (+ ALB em públicas multi-AZ)",
      "Somente subnets em Local Zones sem AZ regional",
      "Zero subnets se os objetos estiverem no S3",
    ], 1,
    "HA multi-AZ exige presença em ≥2 AZ; uma subnet só é SPOF de AZ. S3 não elimina subnets de ALB/EC2. Tip de prova: multi-AZ no requisito → conte AZs no inventário de subnets.",
    p12),
  Q(13, true,
    "Subnet chamada 'private' tem 0.0.0.0/0 → igw em vez de nat. Qual risco de design?",
    [
      "Design incorreto típico: default route IGW é padrão de pública; saída/exposição fica mal definida para 'privada'",
      "Melhora automática a performance do KMS",
      "É obrigatório para RDS Multi-AZ funcionar",
      "Desliga permanentemente a NACL da subnet",
    ], 0,
    "Privadas usam NAT para egress controlado sem tratar a subnet como pública. IGW na default route não é requisito de RDS Multi-AZ nem desliga NACL. Tip de prova: private RT → nat; public RT → igw.",
    p12),
  Q(14, true,
    "SSH no bastion: cliente reporta timeout (não connection refused). Interpretação inicial de rede?",
    [
      "O daemon SSH com certeza recusou ativamente a conexão",
      "Mais compatível com filtragem de path (SG/NACL/rota) do que serviço recusando na porta",
      "Sempre é bucket policy do S3 de logs",
      "Sempre falta Elastic IP no NAT Gateway",
    ], 1,
    "Timeout sugere pacotes filtrados no caminho; connection refused sugere host alcançado e porta fechada. S3 e EIP do NAT não são a primeira hipótese de SSH bastion. Tip de prova: timeout vs refused separa firewall/path de processo down.",
    p12),
  Q(15, true,
    "Qual comando CLI lista rotas e associações de subnet em uma VPC?",
    [
      "aws iam list-users",
      "aws s3 ls",
      "aws ec2 describe-route-tables --filters Name=vpc-id,Values=<vpc-id>",
      "aws sts get-session-token sem papel de rede",
    ], 2,
    "describe-route-tables é o check L3 de path na VPC (0.0.0.0/0 → igw/nat). IAM/S3/STS não mostram RTs de subnet. Tip de prova: sintoma de internet/NAT → describe-route-tables antes de recriar a VPC.",
    p12),
  Q(16, true,
    "ALB em públicas multi-AZ; targets EC2 em privadas. Como o target responde ao ALB na VPC?",
    [
      "Cada target precisa de IP público e rota IGW para falar com o ALB",
      "Tráfego permanece na VPC (rota local); SG do target deve permitir a porta a partir do SG/CIDR do ALB",
      "É obrigatório NAT em cada target só para health check do ALB",
      "NACL deve Deny all entre públicas e privadas",
    ], 1,
    "ALB e targets na mesma VPC usam roteamento local; health não exige IP público no target. NAT e Deny all quebram o desenho. Tip de prova: targets privados + ALB = SG source do ALB, não EIP em cada app.",
    p12),
  Q(17, true,
    "SG: outbound allow all; inbound só TCP 443 de 10.0.0.0/8. Efeito prático?",
    [
      "Nega todo retorno de 443 porque SG seria 'stateless invertido'",
      "Bloqueia obrigatoriamente o DNS da Amazon",
      "Permite iniciar saídas e aceita 443 só de 10.0.0.0/8; retornos de sessões permitidas seguem o modelo stateful",
      "Abre 443 da Internet inteira (0.0.0.0/0)",
    ], 2,
    "SG stateful: inbound restrito a 10.0.0.0/8 na 443 não é aberto ao mundo; outbound all não vira inbound público. Tip de prova: leia o Source do inbound — 10.0.0.0/8 ≠ 0.0.0.0/0.",
    p12),
  Q(18, true,
    "RFP exige sobreviver à queda de uma AZ. Qual anti-padrão de inventário?",
    [
      "Subnets e app em pelo menos duas AZ",
      "ALB cobrindo múltiplas AZ",
      "RDS Multi-AZ quando o engine exige HA de banco",
      "Todos os recursos de produção apenas na AZ-a",
    ], 3,
    "Produção em uma só AZ é SPOF; multi-AZ em rede e serviços é o desenho alinhado ao RFP. Tip de prova: inventário describe-subnets/instances com uma única AZ = falha de HA.",
    p12),
  Q(19, true,
    "Por que usar custom route tables além da main na VPC?",
    [
      "Main é o default; subnets sem associação usam a main — custom segmenta pública (IGW) vs privada (NAT)",
      "Custom route tables não podem ter rota 0.0.0.0/0",
      "Main não pode ter rota local do CIDR",
      "Só a main pode apontar para NAT Gateway",
    ], 0,
    "Separar RTs por tipo de subnet evita que privadas herdem IGW da main por engano. Custom pode ter igw ou nat; rota local existe nas RTs da VPC. Tip de prova: privada na main com 0.0.0.0/0→igw = vazamento de design.",
    p12),
  Q(20, true,
    "Fora de escopo profundo da part VPC foundations (aws-1.2)?",
    [
      "Security Groups e NACLs",
      "NAT Gateway e IGW",
      "Subnets multi-AZ",
      "Transit Gateway deep, PrivateLink lab completo e Client VPN detalhado",
    ], 3,
    "O piloto cobre VPC core, rotas, IGW/NAT, SG/NACL e segmentação. TGW, PrivateLink e Client VPN deep ficam para outras parts. Tip de prova: não force TGW se o cenário resolve com IGW/NAT/SG.",
    p12),
  Q(21, true,
    "NAT em AZ-a; privada só em AZ-b com 0.0.0.0/0 → esse NAT. Qual consideração de design?",
    [
      "Funciona, mas cria dependência cross-AZ (custo/latência) e fragilidade de HA do egress",
      "É proibido em todas as contas AWS sem exceção",
      "Elimina a necessidade de route tables",
      "Torna a subnet automaticamente pública com EIP",
    ], 0,
    "Rota cross-AZ para NAT é possível, porém não ideal para HA e custo de transferência entre AZs. Não é proibição universal nem remove RTs. Tip de prova: HA de egress → NAT (ou padrão moderno) por AZ quando o requisito for rigoroso.",
    p12),
  Q(22, true,
    "Como restringir SSH do bastion apenas ao IP do escritório?",
    [
      "Abrir 0.0.0.0/0 na 22 e confiar só em NACL genérica",
      "SG inbound TCP 22 com Source = CIDR do escritório (e considerar SSM em designs sem 22)",
      "Colocar Elastic IP no RDS Multi-AZ",
      "Remover o IGW de toda a VPC para 'proteger' o bastion",
    ], 1,
    "Least privilege de rede usa Source CIDR (ou SSM Session Manager sem expor 22). 0.0.0.0/0 é fraco; EIP no RDS e remover IGW não segmentam o SSH do bastion com precisão. Tip de prova: bastion 22 → Source corporativo, nunca 0.0.0.0/0 em produção séria.",
    p12),
  Q(23, true,
    "Dois recursos na mesma VPC, subnets diferentes, sem IGW anexado. Eles se comunicam?",
    [
      "Nunca, porque não há Internet",
      "Somente se ambos tiverem NAT Gateway",
      "Sim, via rota local do CIDR da VPC se SG/NACL permitirem",
      "Somente com Transit Gateway obrigatório",
    ], 2,
    "Comunicação intra-VPC usa rota local, independente de Internet. SG/NACL ainda filtram. NAT/TGW não são pré-requisito interno. Tip de prova: sem Internet ≠ sem comunicação VPC interna.",
    p12),
  Q(24, true,
    "NACL default de uma VPC nova (comportamento clássico de prova):",
    [
      "Deny all em tudo de forma permanente e imutável",
      "Allow all inbound e outbound (pode ser customizada depois para endurecer)",
      "Só Allow HTTP 80 e nada mais",
      "Copia automaticamente todas as regras dos Security Groups",
    ], 1,
    "NACL default permite all; o controle fino do dia a dia costuma ser o SG. Você pode criar NACL custom com Deny. Não copia SG. Tip de prova: default NACL permissiva + SG restritivo é o combo comum.",
    p12),
  Q(25, true,
    "App em privada não alcança repositórios na Internet. Ordem mental de Diagnose?",
    [
      "NAT available → rota 0.0.0.0/0 da private RT → SG outbound → NACL → só então app/DNS",
      "Só recriar a VPC inteira como primeiro passo",
      "Só trocar o hostname da EC2",
      "Só desligar o CloudTrail da conta",
    ], 0,
    "Isole o path de saída antes de culpar a aplicação. Recriar VPC ou mexer em hostname/CloudTrail não é o primeiro passo eficiente. Tip de prova: privada sem egress → NAT + rota antes de debug de pacote da app.",
    p12),
  Q(26, true,
    "Banco em subnet privada com rota NAT e alguém propõe Elastic IP na instância DB. Avaliação de design seguro?",
    [
      "EIP no DB é obrigatório para Multi-AZ",
      "EIP melhora a rotação de chaves KMS",
      "Geralmente desnecessário e confunde o design; DB fica em privada sem EIP, acessado só pelo app tier",
      "EIP substitui o Security Group do banco",
    ], 2,
    "DB privado não precisa de EIP; Multi-AZ e KMS não dependem disso. SG continua obrigatório. Tip de prova: EIP em banco privado = cheiro de exposição indevida.",
    p12),
  Q(27, true,
    "Três tiers (web, app, data). Qual padrão de SG reflete least privilege?",
    [
      "Um único SG 0.0.0.0/0 em todas as portas para os três tiers",
      "Mesmo SG com allow all entre todos sem referência de origem",
      "NACL Deny all entre tiers e zero Security Groups",
      "SG do data permite só o SG do app na porta do DB; app permite o SG do web/ALB; borda expõe o mínimo",
    ], 3,
    "Source = SG do tier anterior é o modelo de segmentação SAA. 0.0.0.0/0 amplo e Deny all sem SG quebram operação e least privilege. Tip de prova: tiers → encadeie SGs, não um SG aberto para o mundo.",
    p12),
  Q(28, true,
    "IGW attached à VPC, mas nenhuma route table tem 0.0.0.0/0 → igw. Efeito?",
    [
      "Todas as subnets ficam públicas automaticamente",
      "O NAT Gateway some da conta",
      "O CIDR da VPC é anunciado na Internet pública",
      "Sem rota, as subnets não usam o IGW — path de internet incompleto",
    ], 3,
    "Anexar IGW não basta; a RT da subnet precisa do target. Sem rota, não há path público funcional. Tip de prova: IGW available + ainda sem internet → falta rota 0.0.0.0/0.",
    p12),
  Q(29, true,
    "Checklist de design seguro de VPC (tarefa 1.2) nesta part?",
    [
      "Subnets public/private multi-AZ, rotas IGW/NAT corretas, SG least privilege, NACL ciente, dados sem IP público",
      "Tudo em uma subnet pública com SG 0.0.0.0/0",
      "Somente NACL e zero Security Groups",
      "Somente Transit Gateway sem VPC de aplicação",
    ], 0,
    "O núcleo SAA de rede segura é segmentação, path correto e SG por tier. Subnet única aberta e ausência de SG não atendem a tarefa 1.2. Tip de prova: se a opção ignora privada/multi-AZ/SG, descarte.",
    p12),
  Q(30, true,
    "Usuários HTTPS na Internet; app EC2 em privada. Componentes típicos do desenho?",
    [
      "EIP em cada app instance e porta 22 aberta a 0.0.0.0/0",
      "Somente NACL Deny all em todas as subnets",
      "Access key de IAM user no user-data de cada app",
      "ALB em públicas multi-AZ, targets em privadas, SG em camadas, NAT se a app precisa de egress",
    ], 3,
    "Padrão web seguro: balanceador na borda pública, app privada, SG por tier, NAT para saída. EIP+22 aberta e deny all não são o design Associate típico. Tip de prova: Internet users → ALB pública; app → privada.",
    p12),
];

const q13 = [
  Q(1, false,
    "Pipeline grava artefatos em s3://corp-build/app/v1.2.0.tgz. O que identifica esse objeto no bucket?",
    [
      "A object key (ex. app/v1.2.0.tgz) e versionId se versioning estiver ativo",
      "O Security Group da subnet onde o CI roda",
      "O hostname do NAT Gateway da VPC de build",
      "O ID da route table da subnet pública do ALB",
    ], 0,
    "Objetos S3 são endereçados por bucket + key (prefixos são parte da key); versionId entra com versioning. SG, NAT e route table não identificam o objeto. Tip de prova: se a pergunta é 'onde está o arquivo no S3?', a resposta é key — não componente de VPC.",
    p13),
  Q(2, false,
    "App role precisa ler um prefixo; outra conta também. Quando a bucket policy entra além da IAM identity policy?",
    [
      "Bucket policy só existe se o bucket estiver em Glacier Deep Archive",
      "IAM anexa ao principal; bucket policy anexa ao bucket — útil em cross-account e condições no recurso",
      "IAM nunca pode permitir s3:GetObject em objetos",
      "Bucket policy desliga automaticamente o Block Public Access",
    ], 1,
    "Identity-based autoriza o principal; resource-based no bucket autoriza Principals (inclusive de outra conta) e condições no recurso. Ambas podem Allow/Deny GetObject; BPA é controle separado. Tip de prova: cross-account S3 → pense bucket policy + identity na conta de origem.",
    p13),
  Q(3, false,
    "Compliance exige impedir que policies/ACLs tornem o bucket legível na Internet por engano. Qual controle priorizar?",
    [
      "Habilitar Transfer Acceleration em todos os prefixos",
      "Substituir SSE-S3 por desligar encryption",
      "S3 Block Public Access no bucket e/ou na conta",
      "Criar CRR para outra Região como único controle de exposição",
    ], 2,
    "BPA bloqueia grants e policies públicas acidentais — primeira linha contra Principal * GetObject. Transfer Acceleration e CRR não substituem BPA; desligar encryption piora segurança. Tip de prova: 'público acidental' → BPA antes de discutir CloudFront.",
    p13),
  Q(4, false,
    "Dados sensíveis exigem auditoria e controle de chave de criptografia em repouso. SSE-S3 ou SSE-KMS?",
    [
      "SSE-S3 quando se precisa de CloudTrail de uso de CMK e key policy fina",
      "SSE-KMS (CMK ou AWS managed) quando se precisa de controle/auditoria via KMS",
      "Nenhuma encryption at rest é permitida no S3 Associate",
      "SSE-KMS só funciona se o bucket for público",
    ], 1,
    "SSE-KMS integra KMS para grants, key policy e auditoria; SSE-S3 é mais simples com chaves do S3. Encryption at rest é central no domínio seguro; público não é requisito de KMS. Tip de prova: 'controle de chave/auditoria' → KMS; 'simples default' → SSE-S3.",
    p13),
  Q(5, false,
    "Estagiário sobrescreveu config/prod.json. Versioning está Enabled. Qual benefício direto?",
    [
      "É possível recuperar a versão anterior do objeto (histórico), em vez de depender só de backup externo",
      "O bucket deixa de exigir IAM para GetObject",
      "O bucket torna-se público automaticamente para rollback",
      "O bucket é convertido em sistema de arquivos EBS",
    ], 0,
    "Versioning mantém versões não atuais após overwrite/delete (com delete marker na exclusão). Não remove IAM nem força público. Tip de prova: overwrite acidental + versioning on → list-object-versions / restaurar versão.",
    p13),
  Q(6, false,
    "Logs com acesso <1 GET/mês há 90 dias ainda em Standard sem lifecycle. Qual meta principal de uma rule para STANDARD_IA?",
    [
      "Aumentar o custo de armazenamento quente propositalmente",
      "Desabilitar a criptografia default do bucket",
      "Forçar Block Public Access off no bucket",
      "Reduzir custo de dados pouco acessados (storage class mais barata conforme padrão de acesso)",
    ], 3,
    "Lifecycle transition para IA/Glacier é alavanca do domínio custo; dados frios em Standard incham a fatura. Não desliga encryption nem BPA. Tip de prova: logs frios + custo alto → lifecycle, não 'comprar mais requests'.",
    p13),
  Q(7, false,
    "EC2 app precisa GetObject só em s3://dados/app/*. Qual identidade/permissão é o design preferido?",
    [
      "Access key do root no código da aplicação",
      "Bucket 100% público com Principal * GetObject",
      "IAM role da instância com least privilege s3:GetObject no prefixo app/*",
      "Desligar CloudTrail para o GetObject 'funcionar mais rápido'",
    ], 2,
    "Role + Resource no prefixo é least privilege; root keys e público * são anti-patterns. CloudTrail não libera permissão. Tip de prova: app em EC2 + S3 → role, nunca AKIA no repositório.",
    p13),
  Q(8, false,
    "GetObject retorna AccessDenied com 'explicit deny in an identity-based policy'. O que fazer?",
    [
      "Adicionar Allow s3:* sem inspecionar o Deny",
      "Publicar o objeto com ACL public-read e ignorar IAM",
      "Trocar só a região default do CLI",
      "Localizar e ajustar o statement Deny na policy do principal que bloqueia GetObject",
    ], 3,
    "Deny explícito vence Allow; o remédio é o statement Deny (ou o contexto Condition que o ativa). Allow genérico e ACL pública não 'vencem' Deny e pioram segurança. Tip de prova: texto explicit deny = caçar Deny, não empilhar Allow.",
    p13),
  Q(9, false,
    "Bucket policy Principal \"*\" Action s3:GetObject e get-public-access-block ausente/desligado. Qual risco?",
    [
      "Objetos podem ficar legíveis publicamente na Internet",
      "O bucket é apagado automaticamente em 24h",
      "O versioning desliga sozinho em todos os objetos",
      "O KMS apaga todas as CMK da conta",
    ], 0,
    "Principal * + GetObject com BPA off é o caminho clássico de exposição pública (scanner 200 OK). Não apaga bucket/KMS sozinho. Tip de prova: Principal * GetObject = red flag de bucket público.",
    p13),
  Q(10, false,
    "TShoot de acesso: qual CLI inspeciona o documento de autorização anexado ao bucket?",
    [
      "aws ec2 describe-route-tables",
      "aws iam list-users",
      "aws s3api get-bucket-policy --bucket <nome>",
      "aws sts assume-role sem RoleArn válido",
    ], 2,
    "get-bucket-policy devolve a resource policy do bucket — essencial junto com IAM do caller. Rotas EC2 e list-users não mostram a policy do bucket. Tip de prova: AccessDenied S3 → get-bucket-policy + get-public-access-block + policies da role.",
    p13),
  Q(11, true,
    "get-caller-identity = assumed-role/app-reader. list-attached-role-policies de app-reader = vazio. Bucket policy Allow GetObject só para role data-etl no prefixo reports/*. app-reader falha GetObject em reports/q1.pdf. Causa raiz?",
    [
      "O objeto está em Glacier Deep Archive e por isso IAM é ignorado",
      "O Block Public Access concede GetObject a qualquer role da conta",
      "app-reader não tem Allow (IAM vazio) e a bucket policy não a inclui — só data-etl está autorizada no resource",
      "Falta Internet Gateway na subnet do caller para APIs S3 públicas",
    ], 2,
    "Evidência fecha: sem identity Allow e bucket policy só para data-etl, app-reader não tem caminho Allow efetivo. BPA não libera roles internas; IGW não é requisito típico do endpoint S3 público. Tip de prova: em AccessDenied S3, cruze principal vs Principal da bucket policy e attaches IAM.",
    p13),
  Q(12, true,
    "Compliance aceita encryption at rest gerenciada pelo S3 sem CMK própria. Qual opção descreve SSE-S3?",
    [
      "Criptografia em repouso no servidor com chaves gerenciadas pelo Amazon S3",
      "Obrigatoriedade de usar apenas HTTP sem TLS em todos os puts",
      "Requisito de Client VPN para cada GetObject",
      "Substituição completa do IAM por ACLs públicas",
    ], 0,
    "SSE-S3 cifra at rest com chaves do serviço S3 — opção simples. Não elimina HTTPS, VPN nem IAM. Tip de prova: SSE-S3 = S3-managed keys; SSE-KMS = chaves no KMS.",
    p13),
  Q(13, true,
    "aws s3 rm s3://b/config.json com versioning Enabled. O que acontece em geral?",
    [
      "Todas as versões são apagadas irrecuperáveis imediatamente",
      "O bucket inteiro é removido da conta",
      "Cria-se um delete marker (IsLatest); versões anteriores permanecem recuperáveis",
      "O Block Public Access desliga automaticamente",
    ], 2,
    "Delete com versioning adiciona delete marker; listagem corrente 'some' o objeto, mas list-object-versions mostra histórico. Não apaga o bucket nem desliga BPA. Tip de prova: sumiu + versioning on → delete marker, não 'recriar conta'.",
    p13),
  Q(14, true,
    "Cost Explorer: S3 Standard alto em logs frios; get-bucket-lifecycle-configuration retorna NoSuchLifecycleConfiguration. Problema típico?",
    [
      "Custo de storage mais alto que o necessário sem transition para classes mais baratas",
      "Impossibilidade total de usar IAM no bucket",
      "Perda automática e irreversível de versioning",
      "Bloqueio default de todo PutObject pela AWS",
    ], 0,
    "Sem lifecycle, dados frios permanecem em Standard e elevam custo — domínio 4. IAM e versioning não são desligados por isso. Tip de prova: NoSuchLifecycleConfiguration + Standard em arquivo frio = crie lifecycle.",
    p13),
  Q(15, true,
    "Site estático: S3 website público vs CloudFront com origem privada (menção SAA). Qual contraste de segurança?",
    [
      "São idênticos: ambos exigem Principal * no bucket sempre",
      "Website S3 clássico costuma exigir leitura pública do bucket; CloudFront pode servir origem privada com controle na borda",
      "CloudFront elimina a necessidade de TLS em trânsito",
      "Origem privada força ACL AllUsers READ",
    ], 1,
    "Website endpoint tradicional expõe leitura pública; padrões modernos usam CloudFront + OAI/OAC (ideia) mantendo bucket privado. TLS permanece necessário. Tip de prova: 'sem bucket público' → CloudFront + origem privada, não Principal *.",
    p13),
  Q(16, true,
    "IAM role tem Allow PutObject; bucket policy tem Deny PutObject para essa role. Resultado do put-object?",
    [
      "Put sempre funciona porque IAM vence resource policy",
      "Falha só se faltar Internet Gateway",
      "Falha só se o ETag estiver vazio",
      "Put é negado — Deny explícito na bucket policy prevalece sobre o Allow do IAM",
    ], 3,
    "Deny em resource-based policy bloqueia mesmo com Allow identity. IGW e ETag não explicam explicit deny. Tip de prova: Allow IAM + Deny bucket = AccessDenied; ajuste o Deny.",
    p13),
  Q(17, true,
    "get-public-access-block: BlockPublicAcls e RestrictPublicBuckets = true. Efeito?",
    [
      "Ajuda a impedir exposição pública via ACL e policies públicas no bucket",
      "Desliga o versioning de todos os objetos",
      "Cria SCP de Organizations forçando SSE-KMS em toda a org",
      "Configura CRR para us-west-2 automaticamente",
    ], 0,
    "Flags BPA restringem publicidade acidental. Não desligam versioning nem criam CRR/SCP sozinhas. Tip de prova: scanner público + BPA false/ausente = endureça BPA.",
    p13),
  Q(18, true,
    "Conta B precisa ler bucket da conta A sem tornar o bucket público. Padrão comum?",
    [
      "Compartilhar access key de root da conta A no chat",
      "Bucket policy na A permitindo o principal da B + permissões IAM/role na B",
      "Desligar BPA e abrir Principal * GetObject global",
      "Usar apenas NACL da VPC da B para autorizar a API S3",
    ], 1,
    "Cross-account usa resource policy no bucket A e identity na B (frequentemente AssumeRole). Root keys e * público são inseguros; NACL não autoriza API S3. Tip de prova: cross-account S3 = bucket policy + principal na conta origem.",
    p13),
  Q(19, true,
    "Bucket com default encryption SSE-S3. Cliente faz PutObject sem header x-amz-server-side-encryption. Resultado típico?",
    [
      "O Put é rejeitado em 100% dos casos sem exceção configurável",
      "O bucket é convertido em website hosting automaticamente",
      "O objeto é armazenado cifrado em repouso conforme a default encryption do bucket",
      "O versioning é suspenso automaticamente",
    ], 2,
    "Default encryption aplica SSE no Put quando configurada, sem exigir que o cliente envie o header em muitos fluxos modernos. Não vira website nem desliga versioning. Tip de prova: default encryption = rede de segurança at rest no bucket.",
    p13),
  Q(20, true,
    "Fora de escopo profundo da part S3 foundations (aws-1.3)?",
    [
      "Block Public Access e bucket policy",
      "SSE-S3 vs SSE-KMS (ideia)",
      "Lifecycle transition e versioning",
      "S3 Object Lambda deep, Batch Operations full e Transfer Acceleration deep",
    ], 3,
    "O piloto cobre acesso, BPA, encryption, versioning e lifecycle. Object Lambda, Batch Ops e Transfer Acceleration deep ficam de fora. Tip de prova: não escolha Object Lambda se o problema é só IAM/BPA/lifecycle.",
    p13),
  Q(21, true,
    "Quem consegue get-bucket-policy com sucesso, em geral?",
    [
      "Principal com s3:GetBucketPolicy (sem Deny) — tipicamente role/admin de plataforma",
      "Qualquer usuário anônimo da Internet por default",
      "Somente o serviço EC2 Auto Scaling",
      "Somente quando o NAT Gateway da VPC está desligado",
    ], 0,
    "GetBucketPolicy é API de controle com permissão própria; não é anônima por padrão nem ligada a ASG/NAT. Tip de prova: ler policy do bucket ≠ GetObject em objetos; permissões diferentes.",
    p13),
  Q(22, true,
    "Objeto sumiu na listagem s3 ls; versioning Enabled. Qual próximo check?",
    [
      "Recriar a VPC de produção",
      "list-object-versions (ou console de versões) para delete marker ou VersionId anterior",
      "Desligar rotação de chaves KMS da conta",
      "Abrir 0.0.0.0/0 em um Security Group 'do bucket'",
    ], 1,
    "Com versioning, delete marker e versões explicam o sumiço; restaure a versão. VPC/SG não restauram objeto. Tip de prova: sumiu + versioning → versions/delete marker antes de 'dados perdidos'.",
    p13),
  Q(23, true,
    "Lifecycle expira noncurrent versions após 90 dias. Trade-off custo vs resiliência?",
    [
      "Aumenta sem limite o número de versões para sempre",
      "Desliga o Block Public Access",
      "Reduz custo de versioning antigo e encurta a janela de recuperação dessas versões",
      "Torna o bucket public-read automaticamente",
    ], 2,
    "Expirar versões não atuais corta storage de histórico e reduz RPO de recuperação daquelas versões. Não mexe em BPA/publicidade. Tip de prova: versioning sem expiration = custo escondido.",
    p13),
  Q(24, true,
    "PutObject AccessDenied; get-caller-identity mostra a role correta; IAM da role não lista s3:PutObject. Causa raiz?",
    [
      "Falta Allow s3:PutObject (e Resource do prefixo/bucket) na role",
      "Volume EBS root com pouco espaço no cliente CLI",
      "Falta de Elastic IP associado à role IAM",
      "Hostname DNS privado da VPC incorreto apenas",
    ], 0,
    "Sem PutObject na identity policy o Put falha mesmo com role 'certa' autenticada. EIP, EBS e DNS não concedem API S3. Tip de prova: caller ok + AccessDenied = permissão, não L3 da VPC.",
    p13),
  Q(25, true,
    "No nível desta part, como tratar S3 Cross-Region Replication (CRR)?",
    [
      "Como lab completo multi-region com failover de app obrigatório em toda questão",
      "Como recurso proibido de mencionar no SAA-C03",
      "Como recurso exclusivo de Glacier Deep Archive",
      "Como ideia de resiliência/DR de objetos; implementação deep fora do piloto foundations",
    ], 3,
    "CRR pode aparecer como opção de DR de dados; o lab multi-region completo não é o foco de aws-1.3. Não é proibido nem só Glacier. Tip de prova: foundations = versioning/lifecycle; CRR = ideia, não runbook completo.",
    p13),
  Q(26, true,
    "Bucket policy com Condition aws:SecureTransport = true no Allow. Efeito prático?",
    [
      "Permite apenas HTTP claro sem TLS",
      "Desliga o versioning do bucket",
      "Altera o MTU das ENIs da VPC",
      "Restringe o acesso à API S3 a conexões HTTPS (TLS)",
    ], 3,
    "SecureTransport true exige TLS nas requests que a policy autoriza — controle de dados em trânsito na borda da policy. Não mexe em versioning nem MTU. Tip de prova: Condition SecureTransport = force HTTPS.",
    p13),
  Q(27, true,
    "Allow GetObject em logs/* só para role Logger; user Dev (só console password) tenta GetObject em logs/a.txt. Resultado?",
    [
      "Allow implícito a todos os users da conta",
      "Dev obtém o objeto porque tem senha de console",
      "AccessDenied para Dev — autenticação de console não concede o prefixo logs/",
      "Block Public Access concede GetObject a Dev automaticamente",
    ], 2,
    "AuthN de console ≠ Allow no prefixo; só Logger tem Allow. BPA não libera Dev. Tip de prova: senha OK + GetObject negado = falta de policy no principal.",
    p13),
  Q(28, true,
    "Checklist mental de AccessDenied em s3:GetObject nesta part?",
    [
      "Só recriar o bucket com outro nome global",
      "Só aumentar IOPS do EBS do laptop do analista",
      "Só desligar MFA do root user",
      "Principal → IAM Allow → bucket policy → Deny → BPA → key/ARN → KMS se SSE-KMS",
    ], 3,
    "Ordem lógica isola identidade, policies, BPA, key correta e key policy KMS. Recriar bucket ou mexer em EBS/MFA root não é o primeiro passo. Tip de prova: memorize a ordem principal → allow → deny → BPA → encryption.",
    p13),
  Q(29, true,
    "API online com latência de milissegundos serve objetos a cada request. Glacier Flexible Retrieval vs Standard?",
    [
      "Glacier Flexible é ideal para hot path de API em ms sempre",
      "Standard nunca pode ser cifrado em repouso",
      "Classes Glacier são para arquivo frio com restore/latência maior — inadequadas para leitura quente frequente",
      "Standard é sempre mais barato que qualquer classe Glacier em todos os cenários",
    ], 2,
    "Hot path usa Standard (ou IA com padrão de acesso adequado); Glacier exige restore e latência alta. Standard pode ser cifrado. Tip de prova: API online quente ≠ Glacier Flexible/Deep.",
    p13),
  Q(30, true,
    "Resumo de design S3 foundations no SAA-C03 (esta part):",
    [
      "Bucket sempre Principal * e BPA desligado",
      "Access key de IAM user embutida em todo mobile app",
      "Sempre desligar versioning e lifecycle para 'simplificar'",
      "Privado por padrão (IAM + BPA), encryption adequada, versioning/lifecycle conforme RPO e custo",
    ], 3,
    "Núcleo: least privilege, bloquear público acidental, cifrar, versionar e lifecycle. Público *, keys no app e desligar controles são anti-patterns. Tip de prova: se a opção combina privado + encryption + lifecycle/versioning sob requisito, tende a ser a correta.",
    p13),
];

function writeQuestions(name, arr) {
  const free = arr.filter((q) => q.id <= 10).every((q) => q.isPremium === false);
  const pro = arr.filter((q) => q.id >= 11).every((q) => q.isPremium === true);
  if (!free || !pro) throw new Error(`${name} premium flags`);
  if (arr.length !== 30) throw new Error(`${name} count ${arr.length}`);
  const lens = arr.map((q) => q.explicacao_profunda.length);
  const min = Math.min(...lens);
  const avg = Math.round(lens.reduce((a, b) => a + b, 0) / lens.length);
  if (min < 220) throw new Error(`${name} min expl ${min}`);
  fs.writeFileSync(
    path.join(PARTS, `part-aws-${name}-questions.json`),
    JSON.stringify(arr, null, 2) + "\n",
    "utf8"
  );
  console.log(`questions ${name}: min=${min} avg=${avg} n=${arr.length}`);
}

writeQuestions("1.1", q11);
writeQuestions("1.2", q12);
writeQuestions("1.3", q13);
console.log("questions OK");
